OH_Raspberries: "Baril de Framboise"
OH_Raspberries_Description: ""
OH_Blue_Mushrooms: "Blue Mushrooms Basket"
OH_Blue_Mushrooms_Description: ""
OH_Blueberries: "Blueberry Barrel"
OH_Blueberries_Description: ""
OH_Carrots: "Carrot Barrel"
OH_Carrots_Description: ""
OH_CloudBerries: "CloudBerry Barrel"
OH_CloudBerries_Description: ""
OH_Fish: "Baril de poisson"
OH_Fish_Description: ""
OH_Honey: "Honey Barrel"
OH_Honey_Description: ""
OH_Red_Mushrooms: "Red Mushroom Basket"
OH_Red_Mushrooms_Description: ""
OH_Turnips: "Turnip Barrel"
OH_Turnips_Description: ""
OH_Yellow_Mushrooms: "Yellow_Mushroom Basket"
OH_Yellow_Mushrooms_Description: ""
OH_Thistle: "Thistle Basket"
OH_Thistle_Description: ""
OH_Dandelion: "Dandelion Basket"
OH_Dandelion_Description: ""
OH_Barley: "Barley Barrel"
OH_Barley_Description: ""
OH_Flax: "Flax Barrel"
OH_Flax_Description: ""
OH_Onions: "Onion Barrel"
OH_Onions_Description: ""
OH_Egg_Basket: "Egg Basket"
OH_Egg_Basket_Description: ""
OH_JotunPuffs_Basket: "JotunPuff Basket"
OH_JotunPuffs_Basket_Description: ""
OH_Magecap: "Magecap Basket"
OH_Magecap_Description: ""
OH_RoyalJelly: "RoyalJelly Barrel"
OH_RoyalJelly_Description: ""
OH_Sap_Barrel: "Sap Barrel"
OH_Sap_Barrel_Description: ""
OH_Seedbag: "OdinsSeedBag"
OH_Seedbag_Description: ""