bom_coalmine: "Mine de Charbon"
bom_deposit_coal: "Gisement de Charbon"
bom_coppermine: "Mine de Cuivre"
bom_coppervein: "Gisement de Cuivre"
bom_flintmine: "Mine de Silex"
bom_deposit_flint: "Gisement de Silex"
bom_ironmine: "Mine de Fer"
bom_ironvein: "Gisement de Fer"
bom_tinmine: "Mine d'Étain"
bom_silvermine: "Mine d'Argent"
bom_silvervein: "Gisement d'Argent"
bom_bonemasskey: "Clé de Bonemass"
bom_bonemasskey_description: "Déverrouille les mines d'argent dans les montagnes"
bom_eikthyrkey: "Clé d'Eikthyr"
bom_eikthyrkey_description: "Déverrouille les mines de cuivre et d'étain."
bom_coalminegate: "Porte de la Mine de Charbon"
bom_copperminegate: "Porte de la Mine de Cuivre"
bom_ironminegate: "Porte de la Mine de Fer"
bom_silverminegate: "Porte de la Mine d'Argent"
bom_tinminegate: "Porte de la Mine d'Étain"
